# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'PT-FetchDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!
    pod 'AFNetworking'
  # Pods for PT-FetchDemo

end
