# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'PT-FetchDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

    pod 'Alamofire'
#  pod 'PTFetch', :git=> '../'
  # Pods for PT-FetchDemo

end
